### ISSUE TITLE
[Android] Support android 11 for image & video picking.

### ISSUE THREAD

**Issue by stan-osipov** [StansAssets/com.stansassets.ultimate-mobile#24]

**Comment by LosoncziTamas** [comment]
Hi @stan-osipov 
When can I expect this feature to be released? Thanks in advance!

**Comment by LosoncziTamas** [comment]
In the meanwhile, I implemented a workaround myself. In case anyone needs it:
https://github.com/LosoncziTamas/PhotoPicker

**Comment by stan-osipov** [comment]
Thx.
We made an update to the Android API, which will be release with the next update.
