### ISSUE TITLE
Bug in AN_FirebaseAnalytics when Analytics is disabled

### ISSUE THREAD

**Issue by deJong-IT** [StansAssets/com.stansassets.ultimate-mobile#29]
When messaging is enabled, but analytics is disabled, you get this error:

`Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Runtime/API/Firebase/Analytics/AN_FirebaseAnalytics.cs(9,16): error CS0234: The type or namespace name 'Analytics' does not exist in the namespace 'Firebase' (are you missing an assembly reference?)`

The problem is in the first line of code in AN_FirebaseAnalytics.cs:

```
 #if AN_FIREBASE_MESSAGING && (UNITY_IOS || UNITY_ANDROID)
 #define API_ENABLED
 #endif
```

it should be:

```
 #if AN_FIREBASE_ANALYTICS && (UNITY_IOS || UNITY_ANDROID)
 #define API_ENABLED
 #endif
```

**Comment by stan-osipov** [comment]
Thx for the report. This has been fixed.
The next release with the fix included is 2021.1 The release date is Jan 22. If you would need to get it faster please ping our support team at support@stansassets.com
