### ISSUE TITLE
Issue with AN_FirebaseMessage when using Firebase 6.15.2

### ISSUE THREAD

**Issue by deJong-IT** [StansAssets/com.stansassets.ultimate-mobile#30]
Not possible to enable Firebase Messaging when using Firebase 6.15.2.
The error goes away when using Firebase 7, but due to a bug in Firebase 7 I'd rather not update.

`Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Runtime/API/Firebase/Messaging/Models/AN_FirebaseMessage.cs(26,14): error CS0029: Cannot implicitly convert type 'string' to 'byte[]'`

**Comment by stan-osipov** [comment]
Thx for the report. This has been fixed. 
The next release with the fix included is `2021.1` The release date is Jan 22. If you would need to get it faster please ping our support team at `support@stansassets.com`
