### ISSUE TITLE
Failed to take a picture: 9::User denied permission

### ISSUE THREAD

**Issue by deJong-IT** [StansAssets/com.stansassets.ultimate-mobile#31]
After fixing the ActivityNotFoundException, the camera still doesn't work.
I do get the authentication popup, I accept
Then I get the message: "failed to take a picture: 9::User denied permission."

I'm using this sample code in a new empty project.

 ```
        var camera = UM_Application.CameraService;
 
        int maxThumbnailSize = 1024;
        camera.TakePicture(maxThumbnailSize, (result) => {
            if (result.IsSucceeded)
            {
                UM_Media mdeia = result.Media;
 
                Texture2D image = mdeia.Thumbnail;
                Debug.Log("Thumbnail width: " + image.width + " / height: " + image.height);
                Debug.Log("mdeia.Type: " + mdeia.Type);
                Debug.Log("mdeia.Path: " + mdeia.Path);
            }
            else
            {
                Debug.Log("failed to take a picture: " + result.Error.FullMessage);
            }
        });
```

**Comment by deJong-IT** [comment]
It looks like a bug in AN_Camera:

```
                    if (granted)
                    {
                        var result = new AN_CameraCaptureResult(new SA_Error(9, "User denied permission."));
                        callback.Invoke(result);
                        return;
                    }
```

Should be

```
                    if (!granted)
                    {
                        var result = new AN_CameraCaptureResult(new SA_Error(9, "User denied permission."));
                        callback.Invoke(result);
                        return;
                    }
```



Then the error is gone, but the camera still doesn't popup!

**Comment by stan-osipov** [comment]
We are currently reworking the whole gallery on Android. mainly because it was based on a pretty old 3rd party plugin & now Android 11 has some major changes we need to account for. 

This issue is going to be open for now, and I will be posting updates. Most likely we will rework the whole android camera & gallery API by `2021.2` release at the end of Feb 2021.

As always beta version can be retrieved up on request. 

I expect you will be able to get it mid next week,

**Comment by stan-osipov** [comment]
This is fixed, here is a related case:
https://github.com/StansAssets/com.stansassets.android-native/issues/34

**Comment by Jroch4** [comment]
How can i test the beta version?
