### ISSUE TITLE
DatePicker UI is a bit strange

### ISSUE THREAD

**Issue by imoegirl** [StansAssets/com.stansassets.ultimate-mobile#33]
![DatePicker](https://user-images.githubusercontent.com/57443542/106613809-8f1d3f80-65a5-11eb-89d8-a8f96510bff0.png)

How to make the UI like the one on the right when the DatePicker button is clicked.

**Comment by stan-osipov** [comment]
Looks like this is android, right? Can you give me an Android version, please?

**Comment by imoegirl** [comment]
ios 14，new datepicker issue

发自我的iPhone

在 2021年2月5日，下午11:36，Stanislav Osipov <notifications@github.com> 写道：

﻿

Looks like this is android, right? Can you give me an Android version, please?

**Comment by stan-osipov** [comment]
Please reopen if you can pride more info. So far I will just close the issue.
