### ISSUE TITLE
UM_DatePickerDialog allways shows sunday as first day of week

### ISSUE THREAD

**Issue by andresyebenes** [StansAssets/com.stansassets.ultimate-mobile#35]
iOS users are reporting that the date picker (from UM_DatePickerDialog) is always showing sunday as the first day of the week (usually its monday the first day in most regions).

I think maybe the plugin is not setting correctly the locale in the date picker (from Apple side API):
https://developer.apple.com/documentation/uikit/uidatepicker/1615995-locale
https://developer.apple.com/documentation/uikit/uidatepicker

The correct way should be to use the current user locale settings.
Also, it would be nice to provide a way to manually set the locale with UM_DatePickerDialog.

**Comment by stan-osipov** [comment]
@andresyebenes Agreed and makes sence.
We will work on it
