### ISSUE TITLE
Rate function cant work  on IOS device

### ISSUE THREAD

**Issue by ZJNPRI** [StansAssets/com.stansassets.ultimate-mobile#36]
UM_ReviewController.RequestReview();

This is ok in unity Editor,but no dialog appear in iphone when I test in testflight or Xcode.

Any help?

**Comment by stan-osipov** [comment]
Hey @ZJNPRI thx for the report. 
Can you please give us a device log? It's super simple function so far I suspect that the native part wasn't called, but in the same time this could be an issue on our side.

**Comment by ZJNPRI** [comment]
> Hey @ZJNPRI thx for the report.
> Can you please give us a device log? It's super simple function so far I suspect that the native part wasn't called, but in the same time this could be an issue on our side.

Hi,I have solved the problem.the xcode log show I need add store kit.
So,this is not a bug,just is a small issue about instruction or because I'm  newbee.
Hope you can add instruction upon this function that we need open store kit in services.
Thank you for your reply.
